#include <iostream>

/**
 * Problem 2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be
 *
 * 				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms. 
 * */

//@Author 	Xavier
//@Date		1 Oct 2013

using namespace std;

int main (int argc, char* argv[])
{
	int threshold = 4000000, next = 0, i = 1;
	long sum = 0;
	
	do 
	{
		i += next;
		
		if ((i < threshold) && (i % 2 == 0)) sum += i;
		
		//cout << i << "  ";
		next = i - next;
	}
	while (i < threshold); 
	
	cout << "Soma:   " << sum << endl;
	
	return 0;
}
